language: ruby
rvm:
 - 2.7.3
install:
  - bundle install
  - nvm install 10
  - npm i -g yarn
  - yarn install
services:
  - postgresql
before_script:
  - psql -c 'create database demo_development;' -U postgres
  - psql -c 'create database demo_test;' -U postgres
  - psql -c 'create database demo_production;' -U postgres
  - bundle exec rails webpacker:compile
  - bundle exec rails db:migrate
